[package]
name = "server_2_zivyobraz"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.23", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15"
sysinfo = "0.37.0"
anyhow = "1.0"
chrono = "0.4.41"
